### ISSUE TITLE
missing gnatsd_varz_cpu, is nats.io does not have jetstream ready while exporter start

### ISSUE THREAD

**Issue by tvojacek** [nats-io/prometheus-nats-exporter#242] opened 2023-08-11 16:30 UTC
Almost all metrics are missing is 
if nats.io recover jetstream for too long
while nats expoter start.

reproduce
kill nats.io with big jetstream (300GB)
start nats.io
start nats exporter
wait 5>minutes will nats.io recover jetstream and finish start
check metrics most of metrics are missing.

**Comment by joonas-fi** [comment] 2024-01-05 15:29
Duplicate of #133 ?

**Closed as completed** 2024-01-15 09:19 UTC
